# -*- coding: utf-8 -*-
"""06_04_ExcelLoader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xm4I_pvqz9cVmpkxQviW6uzau17_YXa3

# Excel
"""

pip install -qU langchain-community unstructured openpyxl

from langchain_community.document_loaders import UnstructuredExcelLoader

loader = UnstructuredExcelLoader("/content/titanic.xlsx", mode = "elements")

docs = loader.load()

print(len(docs))

# 문서 출력
print(docs[0].page_content[:200])

# metadata 의 text_as_html 출력
print(docs[0].metadata["text_as_html"][:1000])

"""# DataFrameLoader
- Pandas to docs
"""

import pandas as pd

# Excel 파일 읽기
df = pd.read_excel("/content/titanic.xlsx")

df.head()

from langchain_community.document_loaders import DataFrameLoader

# 데이터 프레임 로더 설정, 페이지 내용 컬럼 지정
loader = DataFrameLoader(df, page_content_column="Name")

# 문서 로드
docs = loader.load()

# 데이터 출력
print(docs[0].page_content)

# 메타데이터 출력
print(docs[0].metadata)
