# -*- coding: utf-8 -*-
"""06_13_LOADER_LLAMAPARSER-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kymJr1ytKD9PikzmJW18zgP94aQWVRU

## Upstage 코드
"""

from langchain_upstage import UpstageLayoutAnalysisLoader

# 파일 경로
file_path = "/content/data/document.pdf"

# Upstage 로더 설정
loader = UpstageLayoutAnalysisLoader(
    file_path=file_path,
    output_type="html",           # HTML 형식 출력
    split="page",                 # 페이지 단위 분할
    use_ocr=True,                 # OCR 사용
    exclude=["header", "footer"], # 헤더와 푸터 제외
    api_key=UPSTAGE_API_KEY       # Upstage API 키
)

# 문서 로드
docs = loader.load()

# 결과 출력
for doc in docs[:3]:
    print(doc.page_content)  # 문서의 텍스트 출력

"""## Lamaparser 코드"""

from langchain_llamaparse import LlamaParse

# 파싱 지침 설정
parsing_instruction = (
    "You are parsing a brief of AI Report. Please extract tables in markdown format."
)

# LlamaParser 설정
parser = LlamaParse(
    use_vendor_multimodal_model=True,
    vendor_multimodal_model_name="openai-gpt4o",
    vendor_multimodal_api_key=OPENAI_API_KEY,
    result_type="markdown",        # Markdown 형식으로 결과 출력
    language="ko",                 # 언어 설정 (한국어)
    parsing_instruction=parsing_instruction,
    api_key=LLAMA_CLOUD_API_KEY    # Llama API 키
)

# 문서 파싱
parsed_docs = parser.load_data(file_path="/content/document.pdf")

# LangChain 문서 형식으로 변환 및 출력
docs = [doc.to_langchain_format() for doc in parsed_docs]
print(docs[-2].page_content)  # 특정 문서의 텍스트 출력