# -*- coding: utf-8 -*-
"""03.LCEL_241226_3_이나은.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WazopuT5BcX2jgr59EHvBxxau6hnHJMn
"""

pip install langchain_teddynote langchain_core langchain_openai

import os

os.environ['OPENAI_API_KEY']=''



"""1. 프롬포트 템플릿 객체 생성 방법"""

#from tempfile import template
from langchain_teddynote.messages import stream_response
from langchain_core.prompts import PromptTemplate

# template 정의
template = "{country}의 수도는 어디인가요?"

prompt = PromptTemplate.from_template(template)

prompt

prompt = prompt.format(country = "미국")

prompt

from langchain_openai import ChatOpenAI

model = ChatOpenAI(
    model = "gpt-3.5-turbo",
    max_tokens = 2048,
    # 0~2 값
    temperature = 0.1
)

template = "{country} 수도는 어디인가요?"

prompt = PromptTemplate.from_template(template)

chain = prompt | model

# country 변수에 입력된 값이 자동으로 치환되어 수행됨
chain.invoke("대한민국").content

print(prompt)

chain

# 숙제 변수가 3개일 경우