# -*- coding: utf-8 -*-
"""04.LCEL_241226_4_이나은.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-xoo9Ru9eIhb7Dza4piidbw4iirYGvf

# 2. PromptTemplate 객체 생성과 동시에 prompt 생성
"""



pip install langchain_teddynote langchain_core langchain_openai

import os

os.environ['OPENAI_API_KEY']=''

from langchain_teddynote.messages import stream_response
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

from langchain_openai import ChatOpenAI

model = ChatOpenAI(
    model = "gpt-3.5-turbo",
    max_tokens = 2048,
    # 0~2 값
    temperature = 0.1
)

template = "{country}의 수도는 어디인가요?"

prompt = PromptTemplate(
    template = template,
    input_variables={"country"}
)

prompt

prompt.format(country = "대한민국")

template = "{country1}과 {country2}, {country3}의 수도는 각각 어디인가요?"

prompt = PromptTemplate(
    template = template,
    input_variables={"country1"},
    partial_variables={"country2": "미국"},
    partial_variabless={"country3": "일본"}
)

prompt

prompt.format(country1 = "대한민국", country3 = "일본")

prompt_partial = prompt.partial(country2 = "미국")

prompt_partial

partial_variabless

chain = prompt_partial | model

chain.invoke({"country1":"대한민국", "country2": "호주", "country2": "일본"})

