# -*- coding: utf-8 -*-
"""05.LCEL_241226_5_이나은.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQAdzOCETIPl-qi6KkHVxXhISbIFqVyC

# 3. 헷갈리지 않도록 날짜 처리
"""

pip install langchain_teddynote langchain_core langchain_openai

from langchain_teddynote.messages import stream_response
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

from datetime import datetime

datetime.now().strftime("%m-%d")

def get_today():
  return datetime.now().strftime("%m-%d")

prompt = PromptTemplate(
    template="오늘의 날짜는 {today}입니다. 오늘이 생일인 유명인 {n}명을 나열해주세요. 생년월일 표기해주세요.",
    input_variables=["n"],
    partial_variables={"today": get_today}
)

from langchain_openai import ChatOpenAI

model = ChatOpenAI(
    model = "gpt-3.5-turbo",
    max_tokens = 2048,
    # 0~2 값
    temperature = 0.1
)

prompt.format(today = "12-26", n = "10")
prompt

prompt_partial = prompt.format(n="10")
prompt_partial

chain = prompt | get_today
chain

chain = prompt | model

chain.invoke({"n": "10"})

