# -*- coding: utf-8 -*-
"""06-00_DocumentLOader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVqTYBSvLA0PzM6Nwz25nfqkdDPj4ifr

### 사용문서 링크
- https://spri.kr/posts/view/23669

## 속성
·page_content : 문서의 내용을 나타내는 문열

·metadata : 문서의 메타데이터를 나타내는 딕셔너리
"""

pip install langchain

from langchain_core.documents import Document

document = Document(page_content= "안녕하세요? 이건 랭체인의 도큐먼트입니다.")

# 도큐먼트의 속성 확인
document.__dict__

"""## DOcument Loader

- PyPDFLoader : PDF 파일을 로드하는 로더
- CSVLoader : CSV 파일을 로드하는 로더
- UnstructuredHTMLLoader : HTML 파일을 로드하는 로더
- JSONLoader : JSON 파일을 로드하는 로더
- TextLoader : 텍스트 파일을 로드하는 로더
- DirectoryLoader : 디렉토리 파일을 로드하는 로더
- UpstageLoader :
- LLaMAIndexLoader :

# 1. PyPDFLoader
"""

FILE_PATH = '/content/SPRI_AI_Brief_2023년12월호_F.pdf'

pip install -qU langchain_community

pip install -qU pypdf

from langchain_community.document_loaders import PyPDFLoader

# 로더 설정
loader = PyPDFLoader(FILE_PATH)

"""# 1.1 Load"""

# PDF 로더
docs = loader.load()

# 문서의 수 확인
len(docs)

docs[0]

docs[1]

"""# 1.2 TextSplit"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=200,
    chunk_overlap=0
)

loader = PyPDFLoader(FILE_PATH)

docs = loader.load_and_split()

split_docs = loader.load_and_split(text_splitter=text_splitter)

print(f'문서의 길이:{len(split_docs)}')

split_docs[0]

"""# 1.4 Iazy_load"""

loader.lazy_load()

for doc in loader.lazy_load():
  print(doc)
  print('=' * 20)

"""# 1.5 aldad()"""

adocs = loader.aload()

# 문서로드
await adocs

