# -*- coding: utf-8 -*-
"""07_07_SPILTCODE_HTML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m720oVJm7ObwWjiejDBngqqdy7RNn0z7
"""

from langchain.text_splitter import HTMLHeaderTextSplitter

# HTML 파일 경로
html = "/content/NAEUN LEE 16d7ad66f39d80829f72da23ebc3c916.html"

# 분할할 헤더를 지정
headers_to_split_on = [
    ("h1", "Header 1"),
    ("h2", "Header 2"),
    ("h3", "Header 3"),
]

# HTMLHeaderTextSplitter 객체 초기화
html_splitter = HTMLHeaderTextSplitter(headers_to_split_on=headers_to_split_on)

# 로컬 HTML 파일을 분할하여 html_header_splits에 결과 저장
html_header_splits = html_splitter.split_text_from_file(html)

# 결과를 .txt 파일로 저장
with open("/content/HTMLHEADERTEXTSPLITTER_RESULT.txt", "w", encoding="utf-8") as f:
    for section in html_header_splits:
        # Document 객체에서 페이지 콘텐츠만 가져옵니다.
        f.write(f"Content: {section.page_content}\n")
        f.write("=" * 50 + "\n")

print("HTMLHEADERTEXTSPLITTER_RESULT.txt")

