# -*- coding: utf-8 -*-
"""11_DirectoryLoader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6FJpND5T_TyiXCw_0-FOPdyfT1_o1Vt
"""

import os

os.getcwd()

pip install -qU langchain_community unstructured

from langchain.document_loaders import DirectoryLoader

# 디렉토리 loader 초기화 (./ 홈 / ** : 하위폴더까지 재귀적으로 포)
#loader = DirectoryLoader('./', glob = '**/*.md')
loader = DirectoryLoader('./sample_data', glob = '*.md')

# 문서 로드
docs = loader.load()

# 문서 계수 계
len(docs)

# 페이지 내용 출력
print(docs[0].page_content[:100])

pip install -qU tqdm

loader = DirectoryLoader(
    './', glob = '**/*.md',
    show_progress = True
)

docs = loader.load()

"""## MultiThread 사용법"""

from langchain_community.document_loaders import TextLoader

# DirectoryLoader를 사용해 '.md' 파일 로드
loader = DirectoryLoader(
    './',  # 현재 디렉토리
    glob="**/*.md",  # 모든 하위 폴더의 .md 파일
    loader_cls=TextLoader  # 텍스트 로더 클래스
)

# 문서 로드
docs = loader.load()

print(docs[0].page_content)

"""## PythonLoader"""

from langchain_community.document_loaders import PythonLoader

loader =  DirectoryLoader(
    './.',
    glob = '**/*.py',
    loader_cls = PythonLoader
)

docs = loader.load()
docs

