# -*- coding: utf-8 -*-
"""11_DirectoryLoader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dscsx1ffRCVO5nd--vFLzBwR5lDnuBu4

# 디렉토리에서 문서를 로드하는 방법

LangChain의 DirectoryLoader는 디스크에서 파일을 읽어 LangChain Document 객체로 변환하는 기능을 구현

이번 튜토리얼은 다음의 내용을 포함
  - 와일드카드 패턴을 포함하여 파일 시스템에서 로드하는 방법
  - 파일 I/O에 멀티스레딩을 사용하는 방법
  - 특정 파일 유형(예: 코드)을 파싱하기 위해 사용자 정의 로더 클래스를 사용하는 방법
  - 디코딩으로 인한 오류와 같은 오류를 처리하는 방법
"""

!pip install -qU langchain_community
!pip install -qU unstructured

from langchain_community.document_loaders import DirectoryLoader

loader = DirectoryLoader("./", glob = "**/*.md")

# 문서 로드
docs = loader.load()

# 문서 개수 계산
len(docs)

# 페이지 내용 출력
print(docs[0].page_content[:100])

"""# Progress Bar 표시"""

!pip install -qU tqdm

loader = DirectoryLoader(
    "./", glob = "**/*.md", show_progress = True
) # 디렉토리 로더 설정

docs = loader.load() # 문서 로드

"""# MultiThread 사용법"""

loader = DirectoryLoader(
    "./", glob = "**/*.md", use_multithreading = True
) # 디렉토리 로더 설정

docs = loader.load() # 문서 로드

"""# Loader Class"""

from langchain_community.document_loaders import TextLoader

# loader_cls 를 TextLoader 로 변경
loader = DirectoryLoader("/content/", glob = "**/*.md", loader_cls = TextLoader)

# 문서 로드
docs = loader.load()

print(docs[0].page_content)

from langchain_community.document_loaders import PythonLoader

# 현재 폴더(.) 의 .py 파일을 모두 조회하여 PythonLoader 로 로드
loader  = DirectoryLoader(",/", glob = "**/*.py", loader_cls = PythonLoader)

docs = loader.load()
docs