# -*- coding: utf-8 -*-
"""CSV_Loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-2p0pL91PMLx3oemsxtGkIDMt2SPUV2

# CSV Loader
"""

pip install -qU langchain_community

from langchain_community.document_loaders.csv_loader import CSVLoader

loader = CSVLoader(file_path = "/content/titanic.csv")

docs = loader.load()

print(len(docs))

"""# MetaData"""

print(docs[0].metadata)

"""# Contents"""

print(docs[0].page_content)

"""# 구조화"""

loader = CSVLoader(
    file_path = "/content/titanic.csv",
    csv_args = {
        "delimiter": ",", # 구분자
        "quotechar": '"', # 인용 부호 문자
        "fieldnames": ["PassengerId", "Survived", "Pclass", "Name", "Sex", "Age", "SibSp", "Parch", "Ticket", "Fare", "Cabin", "Embarked"]
    }
)

docs = loader.load()

print(docs[0].metadata)

"""# Contents, Metadata"""

docs[1].metadata

docs[0].page_content

"""# Export as XML"""

row = docs[1].page_content.split("\n")
row_str = "<row>"
for element in row:
  splitted_element = element.split(":")
  value = splitted_element[-1]
  col = ":".join(splitted_element[:-1])
  row_str += f"<{col}>{value}</{col}>"
row_str += "</row>"

print(row_str)

"""# UnstructuredCSVLoader"""

!pip install -qU unstructured

from langchain_community.document_loaders.csv_loader import UnstructuredCSVLoader

loader = UnstructuredCSVLoader(file_path = "/content/titanic.csv", mode = "elements")

docs = loader.load()

print((docs[0].metadata["text_as_html"][:1000]))

"""# Dataframe Loader"""

import pandas as pd

df = pd.read_csv("/content/titanic.csv")

df.head()

from langchain_community.document_loaders import DataFrameLoader

loader = DataFrameLoader(df, page_content_column = "Name")

docs = loader.load()

print(docs[0].page_content)

print(docs[0].metadata)

for row in loader.lazy_load():
  print(row)
  break