# -*- coding: utf-8 -*-
"""07_03_SPLITCODE_HTML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajYfLADlt10vtdBSF22Ab5Yo_vA6Md0n
"""

from langchain.text_splitter import CharacterTextSplitter

# HTML 파일 읽기
def read_html_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read()

# HTML 파일 경로
file_path = "html_jju.txt"

# HTML 파일 내용 읽기
html_text = read_html_file(file_path)

# 텍스트 분할기 생성
html_splitter = CharacterTextSplitter(
    separator=" ",        # 공백 기준으로 분할
    chunk_size=200,       # 청크 크기 설정
    chunk_overlap=20      # 청크 중복 설정
)

# HTML 텍스트 분할하여 문서 생성
html_docs = html_splitter.split_text(html_text)

# 생성된 문서 출력
for idx, chunk in enumerate(html_docs):
    print(f"Chunk {idx + 1}:\n{chunk}\n")
    print("\n=====================\n")
