# -*- coding: utf-8 -*-
"""07_05_SPLITCODE_PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyxJSeZOePS5BhPg7ZUoDwYwXsRuOTyn
"""

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.schema import Document

# cal_code.txt 파일 읽기
with open("/content/cal_code.txt", "r", encoding="utf-8") as file:
    python_code = file.read()

# RecursiveCharacterTextSplitter 초기화
python_splitter = RecursiveCharacterTextSplitter.from_language(
    language=Language.PYTHON, chunk_size=100, chunk_overlap=0
)

# 코드를 문서로 나누기
python_docs = python_splitter.create_documents([python_code])

# 나뉜 문서 출력
for doc in python_docs:
    print(doc.page_content, end="\n==============================================\n")
